language: R
sudo: false
cache: packages

r_binary_packages:
 - testthat
r_github_packages:
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'lintr::lint_package()’